//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaymanStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buying_info
    {
        public int id { get; set; }
        public string Pname { get; set; }
        public string Supp_name { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Buy_id { get; set; }
    
        public virtual purchase purchase { get; set; }
    }
}
